### PR TITLE
Bump mariadb-operator version

### PR DESCRIPTION
**Pull request by bshephar**
This change bumps the mariadb-operator version and makes the necessary changes to work with the updated version.

### CODE REVIEW

**Review by gibizer — APPROVED** [review]

**Comment by gibizer** [comment]
functional test needs more work 
````
  2024-02-13T07:24:31Z	ERROR	Reconciler error	{"controller": "neutronapi", "controllerGroup": "neutron.openstack.org", "controllerKind": "NeutronAPI", "NeutronAPI": {"name":"neutron-ae04486d-a09b-4103-bf54-838ee4dfe9a3","namespace":"2ea23723-0b75-4918-8c6b-718a06a74ed9"}, "namespace": "2ea23723-0b75-4918-8c6b-718a06a74ed9", "name": "neutron-ae04486d-a09b-4103-bf54-838ee4dfe9a3", "reconcileID": "931f4718-4fa2-496c-8613-89a91edd21af", "error": "Error getting the DB service using label map[app:mariadb cr:mariadb-test-neutron-db-instance]: %!w(<nil>)"}

```

**Comment by bshephar** [comment]
I was using the wrong "name" variable in the `NamespacedName` for the new `SimulateMariaDBAccountCompleted` call. The latest revision fixes that mistake. Let's see if it passes functional tests now.

**Comment by booxter** [comment]
The failure here is weird and I suspect that there's a bug in mariadb handling of explicit databaseUser, see: https://github.com/openstack-k8s-operators/neutron-operator/pull/297

Perhaps I misunderstand something about how the new changes should be adopted, let me know.

I've captured some details about what I think is happening in the commit message in the other PR, but for easier reference, duplicating the message here:

```
    DNM Pass functional tests after mariadb-operator bump

    The flow in mariadb when databaseUser is passed seems broken right now:
    when it's specified, the helper functions:

    First, it creates an account named the same as the database.

    Then later, in getDBWithName, if username != "", it fetches the account
    named as databaseUser. (And, obviously, fails.)

    I have to remove the default databaseUser value here to make it pass
    tests (in which case, the userName is empty.) But it doesn't seem
    correct anyway.

    Posting this is a reference to discuss.

```

**Comment by booxter** [comment]
I think the culprit is this change: https://github.com/openstack-k8s-operators/mariadb-operator/pull/186/files#r1488339028 (left the comment there where I think the problem crept in).

**Comment by gibizer** [comment]
I'm not saying this is the right approach for neutron but basically I did this for nova and placement

```diff
diff --git a/controllers/neutronapi_controller.go b/controllers/neutronapi_controller.go
index b2e36e7..07a6cb8 100644
--- a/controllers/neutronapi_controller.go
+++ b/controllers/neutronapi_controller.go
@@ -400,13 +400,15 @@ func (r *NeutronAPIReconciler) reconcileInit(
 
        // create neutron DB instance
        //
-       db := mariadbv1.NewDatabase(
-               instance.Name,
+       db := mariadbv1.NewDatabaseWithNamespace(
+               "neutron",
                instance.Spec.DatabaseUser,
                instance.Spec.Secret,
                map[string]string{
                        "dbName": instance.Spec.DatabaseInstance,
                },
+               "neutron",
+               instance.Namespace,
        )
        // create or patch the DB
        ctrlResult, err := db.CreateOrPatchDBByName(
diff --git a/test/functional/neutronapi_controller_test.go b/test/functional/neutronapi_controller_test.go
index 807eac9..084b3e5 100644
--- a/test/functional/neutronapi_controller_test.go
+++ b/test/functional/neutronapi_controller_test.go
@@ -783,11 +783,11 @@ var _ = Describe("NeutronAPI controller", func() {
                        DeferCleanup(keystone.DeleteKeystoneAPI, keystone.CreateKeystoneAPI(namespace))
                })
                It("Should set DBReady Condition and set DatabaseHostname Status when DB is Created", func() {
-                       mariadb.SimulateMariaDBAccountCompleted(types.NamespacedName{Namespace: namespace, Name: neutronAPIName.Name})
-                       mariadb.SimulateMariaDBDatabaseCompleted(types.NamespacedName{Namespace: namespace, Name: neutronAPIName.Name})
+                       mariadb.SimulateMariaDBAccountCompleted(types.NamespacedName{Namespace: namespace, Name: "neutron"})
+                       mariadb.SimulateMariaDBDatabaseCompleted(types.NamespacedName{Namespace: namespace, Name: "neutron"})
                        th.SimulateJobSuccess(types.NamespacedName{Namespace: namespace, Name: neutronAPIName.Name + "-db-sync"})
                        NeutronAPI := GetNeutronAPI(neutronAPIName)
-                       Expect(NeutronAPI.Status.DatabaseHostname).To(Equal("hostname-for-" + NeutronAPI.Spec.DatabaseInstance))
+                       Expect(NeutronAPI.Status.DatabaseHostname).To(Equal("hostname-for-" + NeutronAPI.Spec.DatabaseInstance + "." + namespace + ".svc"))
                        th.ExpectCondition(
                                neutronAPIName,
                                ConditionGetterFunc(NeutronAPIConditionGetter),

```

**Pull request merged**
